CREATE Table flows (
    agg_level_pseo VARCHAR NOT NULL,
    inst_level VARCHAR NOT NULL,
    institution VARCHAR NOT NULL,
    degree_level VARCHAR NOT NULL,
    cip_level VARCHAR NOT NULL,
    cipcode VARCHAR NOT NULL,
    grad_cohort VARCHAR NOT NULL,
    grad_cohort_years VARCHAR NOT NULL,
    geo_level VARCHAR NOT NULL,
    geography VARCHAR NOT NULL,
    ind_level VARCHAR NOT NULL,
    industry VARCHAR NOT NULL,
    y1_grads_emp BIGINT,
    y1_grads_emp_instate BIGINT,
    y5_grads_emp BIGINT,
    y5_grads_emp_instate BIGINT,
    y10_grads_emp BIGINT,
    y10_grads_emp_instate BIGINT,
    y1_grads_nme BIGINT,
    y5_grads_nme BIGINT,
    y10_grads_nme BIGINT,
    status_y1_grads_emp INTEGER,
    status_y1_grads_emp_instate INTEGER,
    status_y5_grads_emp INTEGER,
    status_y5_grads_emp_instate INTEGER,
    status_y10_grads_emp INTEGER,
    status_y10_grads_emp_instate INTEGER,
    status_y1_grads_nme INTEGER,
    status_y5_grads_nme INTEGER,
    status_y10_grads_nme INTEGER
)
